### ISSUE TITLE
遇到了一个问题，一直不知道怎么解决

### ISSUE THREAD

**Issue by lele0401** [shiyybua/NER#14]
Traceback (most recent call last):
  File "rnn.py", line 153, in <module>
    embedding = load_word2vec_embedding(vocab_size)
  File "/home/gmy/NER-master/utils.py", line 263, in load_word2vec_embedding
    embeddings[index] = cofes   # 将词和对应的向量存到字典里
ValueError: could not broadcast input array from shape (0) into shape (300)

不知道怎么回事。 谢谢

**Comment by hxh123** [comment]
你的word embedding 文件格式有问题，所以源码里split()不能分出一个单词和300个数字的array.

**Comment by lele0401** [comment]
我的word embedding 是 txt格式的 和这个有关呢？谢谢～

**Comment by hxh123** [comment]
和file的格式没关 是和file里面的内容的格式有关。。。

**Comment by ChallengerL** [comment]
我也遇到了这个问题，请问您解决了吗

**Comment by Gemini77** [comment]
word embedding的格式有关，我刚开始用txt也有问题，后来直接用word2vec的save函数生成.vec格式的向量就解决了
