### ISSUE TITLE
你好数组下标问题

### ISSUE THREAD

**Issue by LuckyPickleZZ** [shiyybua/NER#19]
Traceback (most recent call last):
  File "F:/PyCharm Community Edition 2018.1/Project/venv/rnn.py", line 153, in <module>
    embedding = load_word2vec_embedding(vocab_size)
  File "F:\PyCharm Community Edition 2018.1\Project\venv\utils.py", line 268, in load_word2vec_embedding
    embeddings[index] = coefs   # 将词和对应的向量存到字典里
IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by BillXuce** [comment]
老哥找到解决方案了吗
