### ISSUE TITLE
IndexError: index 2 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by jerryziyan** [shiyybua/NER#21]
Traceback (most recent call last):
  File "E:/python-files/NER/rnn.py", line 153, in <module>
    embedding = load_word2vec_embedding(vocab_size)
  File "E:\python-files\NER\utils.py", line 264, in load_word2vec_embedding
    embeddings[index] = coefs   # 将词和对应的向量存到字典里
IndexError: index 2 is out of bounds for axis 0 with size 2
请问一下作者，这个问题怎么解决啊，弄了半天，不知道怎么办？

**Comment by hsingyang** [comment]
我也是这个报错，不知道楼主解决了没有

**Comment by ChallengerL** [comment]
你好，我也是这个问题，请问解决了吗

**Comment by szq1292718561** [comment]
我也是这个问题，请问怎么解决啊

**Comment by bananagg** [comment]
生成source_vocab.txt出了错，在utils.py中build_word_index方法中，把source.write(word + '\n')改为source.write(str(word) + '\n')

**Comment by bluesky632** [comment]
谢谢bananagg的方法，解决了问题
