### ISSUE TITLE
数据量大求指导

### ISSUE THREAD

**Issue by maergou** [shiyybua/NER#36]
Traceback (most recent call last):
  File "D:/rnn_lstm/rnn.py", line 153, in <module>
    embedding = load_word2vec_embedding(vocab_size)
  File "D:\rnn_lstm\utils.py", line 285, in load_word2vec_embedding
    initializer=tf.constant_initializer(embeddings), trainable=False)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1203, in get_variable
    constraint=constraint)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1092, in get_variable
    constraint=constraint)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 805, in _get_single_variable
    constraint=constraint)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 213, in __init__
    constraint=constraint)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 303, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 779, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\init_ops.py", line 200, in __call__
    self.value, dtype=dtype, shape=shape, verify_shape=verify_shape)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 447, in make_tensor_proto
    "Cannot create a tensor proto whose content is larger than 2GB.")
ValueError: Cannot create a tensor proto whose content is larger than 2GB.

**Comment by DBtxy** [comment]
同样的错误，预训练的词向量太大了，我的有9G
