### ISSUE TITLE
导入包的问题：运行utils.py时，出现from . import config     ImportError: cannot import name 'config'；

### ISSUE THREAD

**Issue by ChallengerL** [shiyybua/NER#37]

**Comment by ChallengerL** [comment]
以及运行rnn.py时，出现    from .utils import *
ModuleNotFoundError: No module named '__main__.utils'; '__main__' is not a package

**Comment by Kiiver** [comment]
前面可以加上当前目录名
比如：
import utils 改为 import NER.utils

**Comment by ChallengerL** [comment]
@Kiiver 运行rnn时出现
Traceback (most recent call last):
  File "G:/NER-master/Rnn.py", line 152, in <module>
    embedding = load_word2vec_embedding(vocab_size)
  File "G:\NER-master\utils.py", line 265, in load_word2vec_embedding
    embeddings[index] = coefs   # 将词和对应的向量存到字典里

ValueError: could not broadcast input array from shape (300) into shape (256)
请问如何解决
