### ISSUE TITLE
运行rnn出现问题

### ISSUE THREAD

**Issue by ChallengerL** [shiyybua/NER#38]
Traceback (most recent call last):
  File "G:/NER-master/Rnn.py", line 152, in <module>
    embedding = load_word2vec_embedding(vocab_size)
  File "G:\NER-master\utils.py", line 265, in load_word2vec_embedding
    embeddings[index] = coefs   # 将词和对应的向量存到字典里
IndexError: index 2 is out of bounds for axis 0 with size 2

求解答

**Comment by slblcx** [comment]
兄弟，你这个问题解决没

**Comment by ChallengerL** [comment]
@slblcx 没有。。

**Comment by ChallengerL** [comment]
@slblcx 你把词向量维度改成301试试

**Comment by slblcx** [comment]
不行啊，改完还是一样的错误，你的改完通过了？

**Comment by slblcx** [comment]
哥们，这个问题我解决了，你在运行代码的时候，会生成一个source_vocab.txt，你打开这个文件看看是不是空的，如果是的话，删除重新运行代码，就行了

**Comment by ChallengerL** [comment]
我还是不行，删了报这个错
发自网易邮箱大师
在2018年6月17日 19:32，slblcx<notifications@github.com> 写道：

哥们，这个问题我解决了，你在运行代码的时候，会生成一个source_vocab.txt，你打开这个文件看看是不是空的，如果是的话，删除重新运行代码，就行了

**Comment by slblcx** [comment]
错误内容是什么？你把错误内容发一下

**Comment by ChallengerL** [comment]
![2a8j9 y 5 5av 5a p0dr](https://user-images.githubusercontent.com/38685885/41507880-ffa4e650-726d-11e8-9531-89b87cd05aae.png)
@slblcx

**Comment by slblcx** [comment]
你可以试试将word强制转换成str试试

**Comment by ChallengerL** [comment]
嗯，我先试试




发自网易邮箱大师
在2018年6月17日 20:40，slblcx<notifications@github.com> 写道：

你可以试试将word强制转换成str试试
