### ISSUE TITLE
rnn预测的时候遇到了问题。

### ISSUE THREAD

**Issue by yorkchu1995** [shiyybua/NER#39]
Traceback (most recent call last):
  File "/Users/YorkChu/PycharmProjects/NER/rnn.py", line 165, in <module>
    net = NER_net("ner", iterator, embedding, BATCH_SIZE)
  File "/Users/YorkChu/PycharmProjects/NER/rnn.py", line 26, in __init__
    self._build_net()
  File "/Users/YorkChu/PycharmProjects/NER/rnn.py", line 66, in _build_net
    self.outputs, self.y, self.seq_length)
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/crf/python/ops/crf.py", line 182, in crf_log_likelihood
    transition_params)
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/crf/python/ops/crf.py", line 109, in crf_sequence_score
    false_fn=_multi_seq_fn)
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/layers/utils.py", line 206, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/smart_cond.py", line 59, in smart_cond
    name=name)
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2063, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1913, in BuildCondBranch
    original_result = fn()
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/crf/python/ops/crf.py", line 95, in _single_seq_fn
    array_ops.concat([example_inds, tag_indices], axis=1))
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2975, in gather_nd
    "GatherNd", params=params, indices=indices, name=name)
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/Users/YorkChu/dev/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: indices.shape[-1] must be <= params.rank, but saw indices shape: [?,11] and params shape: [1,16] for 'ner/cond/GatherNd' (op: 'GatherNd') with input shapes: [1,16], [?,11].

**Comment by blingbling613** [comment]
您好我也遇到了同样的问题请问您解决了嘛

**Comment by ufo5** [comment]
请问您解决了嘛?

**Comment by zhangmingnine** [comment]
请问解决了吗？

**Comment by lihenggit** [comment]
同样的问题，请问解决了吗？

**Comment by MASTERPlECE** [comment]
看看这个
https://github.com/shiyybua/NER/issues/8
