### ISSUE TITLE
预测时出现错误

### ISSUE THREAD

**Issue by amberlwan** [shiyybua/NER#60]
building word index...
source vocabulary file has already existed, continue to next stage.
target vocabulary file has already existed, continue to next stage.
loading word embedding, it will take few minutes...
Traceback (most recent call last):
  File "/home/ontoweb/wanglixia/NER-BiRNN-CRF-shiyybua/rnn.py", line 189, in <module>
    iterator = get_predict_iterator(src_vocab_table, vocab_size, BATCH_SIZE)
  File "/home/ontoweb/wanglixia/NER-BiRNN-CRF-shiyybua/utils.py", line 231, in get_predict_iterator
    pred_dataset = tf.contrib.data.TextLineDataset(pred_file)
AttributeError: 'module' object has no attribute 'TextLineDataset'
，不知道该怎么解决

**Comment by amberlwan** [comment]
已解决
