### ISSUE TITLE
TextLineDataset

### ISSUE THREAD

**Issue by WenkuangWu** [shiyybua/NER#66]

**Comment by WenkuangWu** [comment]
预测时出现下面：

"C:\Program Files\Python35\python.exe" C:/Users/X270/PycharmProjects/kg_learning/rnn.py
building word index...
target vocabulary file has already existed, continue to next stage.
loading word embedding, it will take few minutes...
Traceback (most recent call last):
  File "C:/Users/X270/PycharmProjects/kg_learning/rnn.py", line 160, in <module>
    iterator = get_predict_iterator(src_vocab_table, vocab_size, BATCH_SIZE)
  File "C:\Users\X270\PycharmProjects\kg_learning\utils.py", line 213, in get_predict_iterator
    pred_dataset = tf.contrib.data.TextLineDataset(pred_file)
AttributeError: module 'tensorflow.contrib.data' has no attribute 'TextLineDataset'

Process finished with exit code 1

**Comment by WenkuangWu** [comment]
"C:\Program Files\Python35\python.exe" C:/Users/X270/PycharmProjects/kg_learning/rnn.py
building word index...
target vocabulary file has already existed, continue to next stage.
loading word embedding, it will take few minutes...
Traceback (most recent call last):
  File "C:/Users/X270/PycharmProjects/kg_learning/rnn.py", line 160, in <module>
    iterator = get_predict_iterator(src_vocab_table, vocab_size, BATCH_SIZE)
  File "C:\Users\X270\PycharmProjects\kg_learning\utils.py", line 213, in get_predict_iterator
    pred_dataset = tf.contrib.data.TextLineDataset(pred_file)
AttributeError: module 'tensorflow.contrib.data' has no attribute 'TextLineDataset'

Process finished with exit code 1
