### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by jasonsalex** [shiyybua/NER#7]
使用你给我的wiki.zh.vec训练时,出现以下报错

building word index...
source vocabulary file has already existed, continue to next stage.
loading word embedding, it will take few minutes...
Traceback (most recent call last):
  File "rnn.py", line 153, in <module>
    embedding = load_word2vec_embedding(vocab_size)
  File "/root/NER/utils.py", line 264, in load_word2vec_embedding
    embeddings[index] = coefs   # 将词和对应的向量存到字典里
IndexError: index 391175 is out of bounds for axis 0 with size 391175

**Comment by jasonsalex** [comment]
删除生成的target_xxxxx.txt 文件
