### ISSUE TITLE
IndexError: index 2 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by nan777999** [shiyybua/NER#73]
source vocabulary file has already existed, continue to next stage.
loading word embedding, it will take few minutes...
Traceback (most recent call last):
  File "e:/实体识别/NER-master/rnn.py", line 153, in <module>
    embedding = load_word2vec_embedding(vocab_size)
  File "e:\实体识别\NER-master\utils.py", line 264, in load_word2vec_embedding
    embeddings[index] = coefs   # 将词和对应的向量存到字典里
IndexError: index 2 is out of bounds for axis 0 with size 2

请问这是为什么 。我应该改哪里

**Comment by nan777999** [comment]
改过来了
